# Generated by Django 2.0.3 on 2018-09-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='numofstreet',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
