# Generated by Django 2.0.3 on 2018-09-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20180913_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='numofhouse',
            field=models.TextField(blank=True, max_length=5, null=True),
        ),
    ]
