# Generated by Django 2.0.3 on 2018-09-13 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20180913_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postalcode',
            field=models.CharField(blank=True, help_text='Kod pocztowy', max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Kod musi mieć format xx-xxx', regex='^(^[0-9]{2}(?:-[0-9]{3})?$|^$)')]),
        ),
    ]
