# Generated by Django 2.0.3 on 2018-09-13 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_address_postalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(help_text='Np. abc@xyz.com', max_length=128, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='number',
            field=models.CharField(blank=True, help_text='Numer w formacie 9cyfrowym', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Numer musi mieć format 9 cyfr.', regex='^\\d{9}$')]),
        ),
    ]
